### ISSUE TITLE
getting Cannot find module 'toastr' again with v1.7.1

### ISSUE THREAD

**Issue by poplevente** [knownasilya/ember-toastr#29]
hey, i saw that there were issue like 
Cannot find module 'toastr', for some previous versions. i'm getting the same thing. unless i go back to v1.5
is there a fix for the latests version?

**Comment by knownasilya** [comment]
Can you post the full stack trace so I can see where this is happening.

**Comment by poplevente** [comment]
- stack: Error: Cannot find module 'toastr'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.resolve (internal/module.js:27:19)
    at Class.treeForVendor (pr\node_modules\ember-toastr\index.js:19:43)
    at Class._treeFor (pr\node_modules\ember-cli\lib\models\addon.js:548:33)
    at Class.treeFor (pr\node_modules\ember-cli\lib\models\addon.js:508:21)
    at project.addons.reduce (pr\node_modules\ember-cli\lib\broccoli\ember-app.js:617:25)
    at Array.reduce (native)
    at EmberApp.addonTreesFor (pr\node_modules\ember-cli\lib\broccoli\ember-app.js:615:32)
    at EmberApp._processedVendorTree (pr\node_modules\ember-cli\lib\broccoli\ember-app.js:1120:24)
    at EmberApp._processedExternalTree (pr\node_modules\ember-cli\lib\broccoli\ember-app.js:1148:25)
    at EmberApp.appAndDependencies (pr\node_modules\ember-cli\lib\broccoli\ember-app.js:1295:25)
    at EmberApp.javascript (pr\node_modules\ember-cli\lib\broccoli\ember-app.js:1428:30)
    at EmberApp.toArray (pr\node_modules\ember-cli\lib\broccoli\ember-app.js:1813:12)
    at EmberApp.toTree (pr\node_modules\ember-cli\lib\broccoli\ember-app.js:1837:32)
    at module.exports (pr\ember-cli-build.js:62:14)
    at Builder.setupBroccoliBuilder (pr\node_modules\ember-cli\lib\models\builder.js:51:19)
    at new Builder (pr\node_modules\ember-cli\lib\models\builder.js:29:10)
    at ServeTask.run (pr\node_modules\ember-cli\lib\tasks\serve.js:24:55)
    at Promise.resolve.then (pr\node_modules\ember-cli\lib\models\command.js:243:46)
    at tryCatcher (pr\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:323:19)
    at invokeCallback (pr\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:495:31)
    at pr\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:559:14
    at flush (pr\node_modules\ember-cli\node_modules\rsvp\dist\rsvp.js:2402:5)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)

**Comment by knownasilya** [comment]
Did you install with `ember install ember-toastr`? If not, it didn't install the `toastr` npm dependency which is loaded here https://github.com/knownasilya/ember-toastr/blob/master/index.js#L19

**Comment by poplevente** [comment]
that was it. i was missing the "toastr" dependency. interresting that it wasn't needed for older versions.
