### ISSUE TITLE
Error when using fastboot

### ISSUE THREAD

**Issue by GCorbel** [knownasilya/ember-toastr#31]
When I start the app with fastboot, I have this error message : 

```
/tmp/broccoli-13095zIWfokgP5Vdm/out-390-broccoli_merge_trees/assets/vendor.js:252
    throw new Error('Could not find module `' + id + '` imported from `' + referrer + '`');
    ^

Error: Could not find module `jquery` imported from `(require)`
    at missingModule (/tmp/broccoli-13095zIWfokgP5Vdm/out-390-broccoli_merge_trees/assets/vendor/loader/loader.js:247:1)
    at findModule (/tmp/broccoli-13095zIWfokgP5Vdm/out-390-broccoli_merge_trees/assets/vendor/loader/loader.js:258:1)
    at requireModule (/tmp/broccoli-13095zIWfokgP5Vdm/out-390-broccoli_merge_trees/assets/vendor/loader/loader.js:24:1)
    at /tmp/broccoli-13095zIWfokgP5Vdm/out-390-broccoli_merge_trees/assets/vendor/toastr/toastr.js:472:1
    at /tmp/broccoli-13095zIWfokgP5Vdm/out-390-broccoli_merge_trees/assets/vendor/toastr/toastr.js:15:1
    at /tmp/broccoli-13095zIWfokgP5Vdm/out-390-broccoli_merge_trees/assets/vendor/toastr/toastr.js:470:1
    at Script.runInContext (vm.js:107:20)
    at VMSandbox.eval (/workspace/form/frontend/node_modules/fastboot/src/vm-sandbox.js:14:16)
    at /workspace/form/frontend/node_modules/fastboot/src/ember-app.js:156:15
    at Array.forEach (<anonymous>)
    at EmberApp.loadAppFiles (/workspace/form/frontend/node_modules/fastboot/src/ember-app.js:153:21)
    at EmberApp.retrieveSandboxedApp (/workspace/form/frontend/node_modules/fastboot/src/ember-app.js:201:10)
    at new EmberApp (/workspace/form/frontend/node_modules/fastboot/src/ember-app.js:59:21)
    at FastBoot._buildEmberApp (/workspace/form/frontend/node_modules/fastboot/src/index.js:114:17)
    at new FastBoot (/workspace/form/frontend/node_modules/fastboot/src/index.js:52:10)
    at app.use (/workspace/form/frontend/node_modules/ember-cli-fastboot/index.js:319:29)
    at Layer.handle [as handle_request] (/workspace/form/frontend/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/workspace/form/frontend/node_modules/express/lib/router/index.js:317:13)
    at /workspace/form/frontend/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/workspace/form/frontend/node_modules/express/lib/router/index.js:335:12)
    at next (/workspace/form/frontend/node_modules/express/lib/router/index.js:275:10)
    at err (/workspace/form/frontend/node_modules/ember-cli/lib/tasks/server/middleware/broccoli-watcher/index.js:54:11)
    at watcher.then (/workspace/form/frontend/node_modules/broccoli-middleware/lib/watcher-middleware.js:35:7)
    at tryCatcher (/workspace/form/frontend/node_modules/ember-cli/node_modules/rsvp/dist/lib/rsvp/-internal.js:39:19)
    at invokeCallback (/workspace/form/frontend/node_modules/ember-cli/node_modules/rsvp/dist/lib/rsvp/-internal.js:211:31)
    at /workspace/form/frontend/node_modules/ember-cli/node_modules/rsvp/dist/lib/rsvp/then.js:26:14
    at flush (/workspace/form/frontend/node_modules/ember-cli/node_modules/rsvp/dist/lib/rsvp/asap.js:80:5)
    at process._tickCallback (internal/process/next_tick.js:61:11)
```

It works well when fastboot is disabled.

**Comment by knownasilya** [comment]
Are you using the latest version? https://github.com/knownasilya/ember-toastr/pull/30 should have fixed fastboot support.

I wonder if we need to handle the imports in `index.js` for fastboot..

**Comment by GCorbel** [comment]
Yes I am. I installed ember-toastr "1.7.2"

**Comment by knownasilya** [comment]
I won't be able to get to this for a week (leaving for vacation tonight). Feel free to submit a pull request if you have time.

**Comment by keanedawg** [comment]
I am experiencing the same issue. I know this was reported several months ago, but I am interested in this issue being fixed. 

Not sure if I have time to look into it myself, but I may be interested if no one else is. Our team has been looking into moving some of our ember sites to fastboot.

Either way, just want to re-affirm this issue.

**Comment by knownasilya** [comment]
Will try to investigate what the issue might be. Any help is welcome.
